package com.water.monitoring_and_billing_platform.enums;

public enum AlertType {
    HIGH_WATER_USAGE,
    SUSPECTED_LEAK,
    METER_OFFLINE,
    BILL_OVERDUE,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SYSTEM_NOTIFICATION,
    BILL_GENERATED,
    REGISTRATION_PENDING,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    COMPLAINT_CREATED,
    COMPLAINT_STATUS_UPDATED
}

