package com.water.monitoring_and_billing_platform.service.impl;

import com.water.monitoring_and_billing_platform.entity.*;
import com.water.monitoring_and_billing_platform.enums.BillStatus;
import com.water.monitoring_and_billing_platform.repository.*;
import com.water.monitoring_and_billing_platform.service.BillGenerationService;
import com.water.monitoring_and_billing_platform.service.BillService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.Objects;

@Service
@RequiredArgsConstructor
public class BillServiceImpl implements BillService {

    private final BillRepository billRepository;
    private final ResidentProfileRepository residentProfileRepository;
    private final WaterUsageRepository waterUsageRepository;
    private final BillingCycleRepository billingCycleRepository;
    private final TariffPlanRepository tariffPlanRepository;
    private final WaterMeterRepository waterMeterRepository;
    private final BillGenerationService billGenerationService;
    private final BulkWaterPurchaseRepository bulkWaterPurchaseRepository;
    private final com.water.monitoring_and_billing_platform.service.InvoiceService invoiceService;
    private final com.water.monitoring_and_billing_platform.service.AlertService alertService;

    @Override
    @Transactional
    public Bill generateBillForResident(Long residentId) {
        ResidentProfile resident = residentProfileRepository.findById(residentId)
                .orElseThrow(() -> new IllegalArgumentException("Resident profile not found"));

        BillingCycle cycle = billingCycleRepository.findFirstByActiveTrueOrderByPeriodStartDesc()
                .orElseThrow(() -> new IllegalStateException("No active billing cycle found"));

        if (!cycle.isActive()) {
            throw new IllegalStateException("The selected billing cycle is not active");
        }

        if (billRepository.existsByResidentProfileIdAndBillingCycleId(residentId, cycle.getId())) {
            throw new IllegalStateException("A bill already exists for this resident for the active cycle: " + cycle.getName());
        }

        TariffPlan plan = tariffPlanRepository.findByActiveTrue().stream().findFirst()
                .orElseThrow(() -> new IllegalStateException("No active tariff plan found"));

        WaterMeter meter = waterMeterRepository.findByResidentProfileId(residentId)
                .orElseThrow(() -> new IllegalStateException("No water meter assigned to this resident"));

        List<WaterUsage> usages = waterUsageRepository.findByWaterMeterIdAndReadingDateBetween(
                meter.getId(),
                cycle.getPeriodStart(),
                cycle.getPeriodEnd()
        );
        if (usages.isEmpty()) {
            throw new IllegalArgumentException("No water usage records found for this resident in the active billing cycle.");
        }

        List<WaterUsage> sortedUsages = usages.stream()
                .sorted(java.util.Comparator.comparing(WaterUsage::getReadingDate).thenComparing(WaterUsage::getId))
                .toList();

        double previousReading = sortedUsages.get(0).getPreviousReading();
        double currentReading = sortedUsages.get(sortedUsages.size() - 1).getCurrentReading();

        if (currentReading < previousReading) {
            throw new IllegalArgumentException("Current reading (" + currentReading + ") cannot be less than previous reading (" + previousReading + ")");
        }

        BigDecimal additionalCharge = BigDecimal.ZERO;
        BigDecimal taxRate = new BigDecimal("0.05"); // Default 5% tax

        Bill bill = billGenerationService.prepareBill(
                resident,
                meter,
                cycle,
                plan,
                previousReading,
                currentReading,
                additionalCharge,
                taxRate,
                "Generated by core billing engine"
        );

        SharedCostDistribution dist = calculateSharedCostForResident(resident, cycle.getId());
        bill.setSharedWaterCost(dist.sharedCost);
        bill.setDistributionStrategy(dist.strategy);

        BigDecimal currentAmount = bill.getAmount() != null ? bill.getAmount() : BigDecimal.ZERO;
        BigDecimal currentTotal = bill.getTotalAmount() != null ? bill.getTotalAmount() : BigDecimal.ZERO;

        bill.setAmount(currentAmount.add(dist.sharedCost));
        bill.setTotalAmount(currentTotal.add(dist.sharedCost));

        bill.setBillStatus("GENERATED");
        bill.setPaymentStatus("UNPAID");
        bill.setStatus(BillStatus.UNPAID);
        bill.setPaid(false);

        Bill savedBill = billRepository.save(bill);
        invoiceService.generateInvoice(savedBill);

        // Trigger in-app notification
        alertService.createInAppNotification(
                resident.getUser(),
                resident,
                resident.getCommunity(),
                "New Bill Generated",
                "A new bill of Rs. " + savedBill.getTotalAmount() + " has been generated for cycle: " + cycle.getName(),
                com.water.monitoring_and_billing_platform.enums.AlertType.BILL_GENERATED,
                com.water.monitoring_and_billing_platform.enums.AlertSeverity.LOW,
                savedBill.getId()
        );

        return savedBill;
    }

    @Override
    public Bill getBillById(Long id) {
        return billRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Bill not found"));
    }

    @Override
    public List<Bill> getBillsByResidentId(Long residentId) {
        return billRepository.findByResidentProfileId(residentId);
    }

    @Override
    public List<Bill> getBillsByCommunityId(Long communityId) {
        return billRepository.findByResidentProfileCommunityId(communityId);
    }

    public static class SharedCostDistribution {
        public BigDecimal sharedCost = BigDecimal.ZERO;
        public String strategy = "EQUAL";
    }

    public SharedCostDistribution calculateSharedCostForResident(
            ResidentProfile resident,
            Long billingCycleId
    ) {
        SharedCostDistribution dist = new SharedCostDistribution();
        dist.sharedCost = BigDecimal.ZERO;
        dist.strategy = "EQUAL";

        if (resident == null || billingCycleId == null) {
            return dist;
        }

        List<BulkWaterPurchase> purchases = bulkWaterPurchaseRepository.findByBillingCycleIdAndCommunityId(
                billingCycleId,
                resident.getCommunity().getId()
        );

        if (purchases.isEmpty()) {
            return dist;
        }

        BigDecimal totalCost = purchases.stream()
                .map(BulkWaterPurchase::getTotalCost)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        if (totalCost.compareTo(BigDecimal.ZERO) <= 0) {
            return dist;
        }

        List<ResidentProfile> communityResidents = residentProfileRepository.findByCommunityIdAndActiveTrue(resident.getCommunity().getId());
        if (communityResidents.isEmpty()) {
            return dist;
        }

        boolean hasOccupancy = communityResidents.stream()
                .allMatch(r -> r.getUnit() != null && r.getUnit().getOccupancy() != null && r.getUnit().getOccupancy() > 0);

        boolean hasArea = communityResidents.stream()
                .allMatch(r -> r.getUnit() != null && r.getUnit().getArea() != null && r.getUnit().getArea() > 0.0);

        if (hasOccupancy) {
            dist.strategy = "PROPORTIONAL_OCCUPANCY";
            double totalOccupancy = communityResidents.stream()
                    .map(r -> r.getUnit().getOccupancy())
                    .filter(Objects::nonNull)
                    .mapToDouble(Integer::doubleValue)
                    .sum();
            
            if (totalOccupancy > 0) {
                double residentOccupancy = (resident.getUnit() != null && resident.getUnit().getOccupancy() != null) ? resident.getUnit().getOccupancy() : 0.0;
                dist.sharedCost = totalCost.multiply(BigDecimal.valueOf(residentOccupancy))
                        .divide(BigDecimal.valueOf(totalOccupancy), 2, java.math.RoundingMode.HALF_UP);
            }
        } else if (hasArea) {
            dist.strategy = "PROPORTIONAL_AREA";
            double totalArea = communityResidents.stream()
                    .map(r -> r.getUnit().getArea())
                    .filter(Objects::nonNull)
                    .mapToDouble(Double::doubleValue)
                    .sum();

            if (totalArea > 0) {
                double residentArea = (resident.getUnit() != null && resident.getUnit().getArea() != null) ? resident.getUnit().getArea() : 0.0;
                dist.sharedCost = totalCost.multiply(BigDecimal.valueOf(residentArea))
                        .divide(BigDecimal.valueOf(totalArea), 2, java.math.RoundingMode.HALF_UP);
            }
        } else {
            dist.strategy = "EQUAL";
            dist.sharedCost = totalCost.divide(BigDecimal.valueOf(communityResidents.size()), 2, java.math.RoundingMode.HALF_UP);
        }

        return dist;
    }

    @Override
    public BigDecimal estimateBillForResident(Long residentId, Long billingCycleId) {
        ResidentProfile resident = residentProfileRepository.findById(residentId)
                .orElseThrow(() -> new IllegalArgumentException("Resident profile not found"));

        BillingCycle cycle = billingCycleRepository.findById(billingCycleId)
                .orElseThrow(() -> new IllegalArgumentException("Billing cycle not found"));

        TariffPlan plan = tariffPlanRepository.findByActiveTrue().stream().findFirst()
                .orElseThrow(() -> new IllegalStateException("No active tariff plan found"));

        Optional<WaterMeter> meterOpt = waterMeterRepository.findByResidentProfileId(residentId);
        if (meterOpt.isEmpty()) {
            return BigDecimal.ZERO;
        }
        WaterMeter meter = meterOpt.get();

        List<WaterUsage> usages = waterUsageRepository.findByWaterMeterIdAndReadingDateBetween(
                meter.getId(),
                cycle.getPeriodStart(),
                cycle.getPeriodEnd()
        );
        
        double unitsConsumed = 0.0;
        double previousReading = meter.getCurrentReading();
        double currentReading = meter.getCurrentReading();

        if (!usages.isEmpty()) {
            List<WaterUsage> sortedUsages = usages.stream()
                    .sorted(java.util.Comparator.comparing(WaterUsage::getReadingDate).thenComparing(WaterUsage::getId))
                    .toList();
            previousReading = sortedUsages.get(0).getPreviousReading();
            currentReading = sortedUsages.get(sortedUsages.size() - 1).getCurrentReading();
            if (currentReading >= previousReading) {
                unitsConsumed = BigDecimal.valueOf(currentReading)
                        .subtract(BigDecimal.valueOf(previousReading))
                        .setScale(2, java.math.RoundingMode.HALF_UP)
                        .doubleValue();
            }
        }

        BigDecimal taxRate = new BigDecimal("0.05"); // Default 5% tax
        
        Bill tempBill = billGenerationService.prepareBill(
                resident,
                meter,
                cycle,
                plan,
                previousReading,
                currentReading,
                BigDecimal.ZERO,
                taxRate,
                "Simulated Estimation"
        );

        SharedCostDistribution dist = calculateSharedCostForResident(resident, cycle.getId());
        BigDecimal total = tempBill.getTotalAmount() != null ? tempBill.getTotalAmount() : BigDecimal.ZERO;
        return total.add(dist.sharedCost);
    }
}
