spring.application.name=monitoring-and-billing-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/water_monitoring_db
spring.datasource.username=water_admin
spring.datasource.password=YourStrongPassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect