spring.application.name=monitoring-and-billing-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/water_monitoring_db
spring.datasource.username=water_admin
spring.datasource.password=water@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=8Qk5mR9vT2xY7nL4pA6sD3fG8hJ1kL9zQwErTyUiOpAsDfGhJkLzXcVbNm123456
jwt.expiration=86400000