spring.datasource.url=jdbc:postgresql://ep-billowing-feather-aisy2cco-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4vGwaJ6tlDmd

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.schema=public

jwt.secret=8Qk5mR9vT2xY7nL4pA6sD3fG8hJ1kL9zQwErTyUiOpAsDfGhJkLzXcVbNm123456
jwt.expiration=86400000

frontend.base-url=http://localhost:5173
app.frontend.url=${FRONTEND_URL:https://web-based-water-usage-monitoring-an.vercel.app}
invitation.expiry-days=7

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=${SPRING_MAIL_FROM}

